import { colors as sharedColors } from "@cooking/design-tokens";

export const colors = {
  canvas: sharedColors.canvas,
  surface: sharedColors.surface,
  subtleSurface: sharedColors.subtleSurface,
  ink: sharedColors.ink,
  mutedInk: sharedColors.mutedInk,
  terracotta: sharedColors.action,
  terracottaPressed: sharedColors.actionPressed,
  sage: sharedColors.sage,
  divider: sharedColors.divider,
  error: sharedColors.error,
  success: sharedColors.success,
  onAction: sharedColors.onAction,
  primary: sharedColors.action,
  primaryContainer: sharedColors.subtleSurface,
  primaryFixed: sharedColors.subtleSurface,
  onPrimaryFixed: sharedColors.actionPressed,
  onPrimary: sharedColors.onAction,
  background: sharedColors.canvas,
  surfaceContainerLow: sharedColors.subtleSurface,
  surfaceContainer: sharedColors.subtleSurface,
  surfaceContainerHigh: sharedColors.divider,
  white: sharedColors.surface,
  onSurface: sharedColors.ink,
  onSurfaceVariant: sharedColors.mutedInk,
  border: sharedColors.divider,
  errorContainer: "#FEE4E2",
  onError: sharedColors.onAction,
  successContainer: "#E8F1E8",
  onSuccess: sharedColors.success,
  recipePaper: sharedColors.canvas,
  recipeCard: sharedColors.surface,
  recipeLine: sharedColors.divider,
  accentSoft: sharedColors.subtleSurface,
  accent: sharedColors.action,
  tipsCallout: sharedColors.subtleSurface,
} as const;

export type ColorToken = keyof typeof colors;
